### ISSUE TITLE
PHP 7.3 support

### ISSUE THREAD

**Issue by rentalhost** [ricardofiorani/oembed#1]
PHP 7.4 still in development (actually RC4 phase). So, there are some specific reason to not support 7.3 that is currently supported at production servers?

I am upgrading from your previous package [ricardofiorani/php-video-url-parser](https://github.com/ricardofiorani/php-video-url-parser) and I can't due this issue. 😢

**Comment by ricardofiorani** [comment]
@rentalhost Hi,

Since PHP 5.3 reached it's support end-of-life on June 3rd this year, I decided to upgrade the `ricardofiorani/php-video-url-parser` with PHP 7 support only, however, due to the way that the lib was architectured, I decided to abandon it in favour of a whole rewriting of the lib with a different approach, which was following the oEmbed format.

The reason it was made on PHP 7.4 is because I wanted to make it modern and to last longer, also I wanted to give time for people to test it while PHP 7.4 is not released.

Meanwhile, if your production application runs on PHP 5.3, I recommend you to stick with `ricardofiorani/php-video-url-parser` until your application is PHP 7.4 ready.

Sorry for any problem :(

**Comment by rentalhost** [comment]
Sorry, I mean PHP 7.3 instead 5.3, and PHP 7.4 where I wrote 5.4. I have updated.

**Comment by christianmagill** [comment]
@ricardofiorani Is there anything that will actually stop the package from working on 7.3 versions?

**Comment by ricardofiorani** [comment]
> @ricardofiorani Is there anything that will actually stop the package from working on 7.3 versions?

Unfortunately yes. It would require some refactoring to make it work on PHP 7.3.
On top of my mind the only feature I remember that is on PHP 7.4 and not on 7.3 are typed properties, but there are other backward incompatibilities in there I think.

**Comment by ricardofiorani** [comment]
I'm closing this as there is no solution achieved or action required.
